services:
  # A Docker web service
  - type: web
    name: apf-feature-flag-app
    env: docker
    repo: https://github.com/mustmodify/bandiera
    plan: starter
    branch: main
    #rootDir: /
    dockerCommand: ./entrypoint.sh # optional (defaults to Dockerfile command)
    #numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: DB_URL
        fromDatabase:
          name: apf-feature-flag-data
          property: connectionString

databases:
  - name: apf-feature-flag-data

# https://render.com/docs/blueprint-spec
